# Generated by Django 5.2.13 on 2026-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_goals', models.IntegerField()),
                ('visitant_goals', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
